//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlockbusterVideo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string Studio { get; set; }
        public string Released { get; set; }
        public string Status { get; set; }
        public string Sound { get; set; }
        public string Versions { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Rating { get; set; }
        public string Year { get; set; }
        public string Genre { get; set; }
        public string Aspect { get; set; }
        public string UPC { get; set; }
        public Nullable<System.DateTime> DVDReleaseDate { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
    }
}
